project_id = "epitasign"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true

[auth]
enabled = true
site_url = "epitasign://auth"
additional_redirect_urls = ["epitasign://auth"]

[functions.request-attendance-token]
verify_jwt = true

[functions.submit-attendance-signature]
verify_jwt = true
